name: Update MindTrack Data

on:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Update Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

        run: |
          cd backend
          python update_data.py